### ISSUE TITLE
Make navbar and landing page logo hide/show

### ISSUE THREAD

**Issue by gbergere** [gbergeret-cloud/company-website#10]
The idea here is to make the navbar menu appear when scrolling down to avoid having it breaking the user experience when landing on the website. Eventually the idea would be the have the company logo from the landing page to move up and resize to fit in the middle of the navbar and the other way when scroll back up.

For now, we can simply use opacity and increase the opacity of the navbar while reducing the opacity of the landing page logo so one appear while the other disappear.

We want to do this in order to avoid the redundancy of having the same logo next to each other.

**Comment by gbergere** [comment]
@briardg I've made a few tickets here so it is easier to share work.

I would appreciate some help on this one.

**Comment by briardg** [comment]
✅
